project:
  type: website
  output-dir: docs

website:
  title: "Piercing Insight"
  site-url: https://sjpierce.github.io
  description: "Steven. J. Pierce's personal blog."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: packages.qmd
        text: R Packages
      - href: presentations.qmd
        text: Presentations
      - about.qmd
    right:
      - icon: rss
        href: index.xml
format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
