project:
  type: website
  output-dir: docs

website:
  title: "Piercing Insight"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: packages.qmd
        text: R Packages
      - href: presentations.qmd
        text: Presentations
      - about.qmd
format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
