---
title: "About"
author: 
  - name: Steven J. Pierce
    orcid: 0000-0002-0679-3019
    email: pierces1@msu.edu
date-modified: last-modified
date-format: YYYY-MM-DD HH:mm:ss z
about: 
  template: marquee
  links: 
    - icon: github
      text: GitHub
      href: https://github.com/sjpierce
    - text: "{{< ai google-scholar >}} Google Scholar"
      href: https://scholar.google.com/citations?user=-ZHBcFEAAAAJ&hl=en
    - text: "{{< ai orcid >}} ORCID"
      href: https://orcid.org/0000-0002-0679-3019
format: 
  html:
    toc: true
    toc-depth: 3
    toc-location: left
    number-sections: true
    number-depth: 3
    code-fold: true
    code-tools: true
    code-line-numbers: false
    embed-resources: true 
    anchor-sections: true
    link-external-icon: true
execute:
  eval: true
  echo: fenced
  output: true
  warning: true
  error: true
  include: true
knitr:
  opts_chunk: 
    message: true
---

I am an applied statistician, researcher, and program evaluator at 
[Michigan State University](https://msu.edu), working in the 
[Center for Statistical Training and Consulting (CSTAT)](https://cstat.msu.edu). 
My PhD is in Ecological-Community Psychology but I've been working at CSTAT
since 2009 and have applied my skills to a wide array of studies spanning many
different academic disciplines, research designs, and topic areas.

Some of my current work focuses on:

* A cost-benefit analysis of 
  [EFNEP](https://www.nifa.usda.gov/grants/programs/capacity-grants/efnep/expanded-food-nutrition-education-program) 
  utilizing biomarkers of chronic disease risk.   
* Examining the effect of cognitive-behavioral therapy interventions on 
  psychological, functional, and disease-related outcomes in youth with 
  functional abdominal pain disorders or with childhood-onset lupus.
* Predicting the performance of medical students on licensing examinations. 
* Examining the effect of a public preschool program on student retention, 
  absenteeism, and standardized test scores for English and math during 
  kindergarten through sixth grade. 
  
:::{.callout-tip title="Available for Grant & Contract Work"}
*Collaboration and consulting with researchers, organizations, businesses,*
*government agencies, and other academic institutions are all part of my job at* 
*CSTAT*. If you want to discuss engaging my professional services, either email 
me directly or visit the [CSTAT website](https://cstat.msu.edu), click the 
`Request a Consultation` button, then list me as the preferred consultant when 
filling out our project intake form. 

You can see more information at:

* [https://cstat.msu.edu/collaborate](https://cstat.msu.edu/collaborate), and 
* [https://cstat.msu.edu/collaborate/grants-contracts-support](https://cstat.msu.edu/collaborate/grants-contracts-support).
:::